insert into public.leads (
  first_name,
  last_name,
  email,
  phone,
  position,
  city,
  state,
  country,
  linkedin,
  seniority,
  functions,
  org_name,
  org_website,
  org_linkedin,
  founded_year,
  industry,
  size,
  description,
  specialties,
  org_city,
  org_state,
  org_country
) values
('Jordan', 'Banks', 'jordan.banks@growthops.com', '+1-512-555-0193', 'Head of Revenue', 'Austin', 'TX', 'USA', 'https://www.linkedin.com/in/jordanbanks', 'Director', '{Sales}', 'GrowthOps', 'https://growthops.com', 'https://www.linkedin.com/company/growthops', 2018, 'SaaS', '51-200', 'Revenue intelligence platform for GTM teams.', '{Revenue Operations, Sales Enablement}', 'Austin', 'TX', 'USA'),
('Priya', 'Desai', 'priya.desai@medinova.io', '+44-20-7946-0001', 'VP Clinical Partnerships', 'London', null, 'UK', 'https://www.linkedin.com/in/priyadesai', 'VP', '{Partnerships, Strategy}', 'MediNova', 'https://medinova.io', 'https://www.linkedin.com/company/medinova', 2012, 'Healthcare', '201-500', 'AI diagnostics for oncology clinics.', '{Medical Imaging, Diagnostics}', 'London', null, 'UK'),
('Hugo', 'Martinez', null, null, 'Senior Data Scientist', 'Barcelona', null, 'Spain', 'https://www.linkedin.com/in/hugomartinez', 'Senior IC', '{Data Science}', 'Visionary Retail', 'https://visionaryretail.com', 'https://www.linkedin.com/company/visionary-retail', 2006, 'Retail', '1000+', 'Omnichannel retail intelligence.', '{Computer Vision, Analytics}', 'Barcelona', null, 'Spain'),
('Lena', 'Kowalski', 'lena.kowalski@polargrid.io', '+48-22-555-2900', 'CTO', 'Warsaw', null, 'Poland', 'https://www.linkedin.com/in/lenakowalski', 'C-Level', '{Engineering, Product}', 'PolarGrid', 'https://polargrid.io', 'https://www.linkedin.com/company/polargrid', 2015, 'Manufacturing', '501-1000', 'Smart grid monitoring for industrial plants.', '{IoT, Predictive Maintenance}', 'Gdansk', null, 'Poland'),
('Marcus', 'Nguyen', 'marcus.nguyen@finpath.co', '+1-415-555-7721', 'Product Manager', 'San Francisco', 'CA', 'USA', 'https://www.linkedin.com/in/marcusnguyen', 'Manager', '{Product}', 'FinPath', 'https://finpath.co', 'https://www.linkedin.com/company/finpath', 2020, 'FinTech', '51-200', 'Embedded finance orchestration tools.', '{Payments, Banking-as-a-Service}', 'San Francisco', 'CA', 'USA');
